### PR TITLE
adding .xml fils

### PR DESCRIPTION
**Pull request by vintech20**
Please review the listed files and approved
Have added the necessary .xml files for our projects

### CODE REVIEW

**Review by vlonje — APPROVED** [review]
Codes have been reviewd and they are ok.
I recommend for you to merge the codes to the pro branch

**Comment by vlonje** [comment]
Codes are ok

**Comment by megastellas** [comment]
Thanks Vin, I guess we are now waiting for Allen to complete his review before we can merge the codes

**Comment by anebota** [comment]
Verified and approved

**Review by vlonje — APPROVED** [review]
The codes have been reviewed and are ok for merging

**Review by anebota — APPROVED** [review]
Verified and approved

**Comment by megastellas** [comment]
This branch has been successfully merged. I will go ahead and delete the branch now

**Pull request merged**
