### PR TITLE
updated pom.xml-file

### PR DESCRIPTION
**Pull request by anebota**
Please verify and approve

### CODE REVIEW

**Review by vlonje — APPROVED** [review]
Approved. Codes are OK

**Review by vintech20 — APPROVED** [review]
Yes the codes are OK, you can merge

**Comment by anebota** [comment]
https://meet.jit.si/gitHub

Allen Nebota E.
Mobile: (0945) 100 3746
Viber: (0945) 100 3746
Home: (02) 7910 2736

**Comment by anebota** [comment]
https://meet.jit.si/github



Allen Nebota E.
Mobile: (0945) 100 3746
Viber: (0945) 100 3746
Home: (02) 7910 2736

**Comment by anebota** [comment]
https://meet.google.com/vya-aerw-stp

Allen Nebota E.
Mobile: (0945) 100 3746
Viber: (0945) 100 3746
Home: (02) 7910 2736

**Comment by anebota** [comment]
https://meet.google.com/zvf-udmm-uax

Allen Nebota E.
Mobile: (0945) 100 3746
Viber: (0945) 100 3746
Home: (02) 7910 2736

**Pull request merged**
